/**
 * Reddit Intelligence Agent — Evidence pack export
 */

import { z } from 'zod';
import { exportEvidencePackSchema } from './schemas.js';
import type { EvidencePack } from '../types/index.js';

export class ExportTools {
  async exportEvidencePack(params: z.infer<typeof exportEvidencePackSchema>): Promise<string> {
    const data = params.data;
    const now = new Date().toISOString();

    if (params.format === 'json') {
      const pack: EvidencePack = {
        title: params.title,
        generated_at: now,
        summary: this.generateSummary(data),
        sections: this.extractSections(data),
        urls_cited: this.countUrls(data),
        data_points: this.countDataPoints(data),
      };
      return JSON.stringify(pack, null, 2);
    }

    // Markdown format
    return this.toMarkdown(params.title, now, data);
  }

  private generateSummary(data: unknown): string {
    if (!data || typeof data !== 'object') return 'No data provided';
    const d = data as Record<string, unknown>;

    const parts: string[] = [];
    if (d.total_found) parts.push(`${d.total_found} findings`);
    if (d.pain_points && Array.isArray(d.pain_points)) parts.push(`${d.pain_points.length} pain points`);
    if (d.workarounds && Array.isArray(d.workarounds)) parts.push(`${d.workarounds.length} workarounds`);
    if (d.leads && Array.isArray(d.leads)) parts.push(`${d.leads.length} leads`);
    if (d.score && typeof d.score === 'object') {
      const s = d.score as Record<string, unknown>;
      if (s.total) parts.push(`opportunity score: ${s.total}/100`);
    }

    return parts.length > 0 ? parts.join(', ') : 'Analysis complete';
  }

  private extractSections(data: unknown): EvidencePack['sections'] {
    if (!data || typeof data !== 'object') return [];
    const d = data as Record<string, unknown>;
    const sections: EvidencePack['sections'] = [];

    const arrayFields = ['pain_points', 'workarounds', 'leads', 'feature_gaps', 'objections', 'competitors'];
    for (const field of arrayFields) {
      if (d[field] && Array.isArray(d[field])) {
        sections.push({
          heading: field.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
          findings: (d[field] as Array<Record<string, unknown>>).slice(0, 20).map(item => ({
            text: String(item.text ?? item.title ?? item.description ?? item.competitor ?? ''),
            source_url: String(item.source_url ?? item.url ?? ''),
            subreddit: String(item.subreddit ?? ''),
            score: Number(item.score ?? item.upvotes ?? 0),
            date: item.created_utc ? new Date(Number(item.created_utc) * 1000).toISOString().split('T')[0] : '',
          })),
        });
      }
    }

    return sections;
  }

  private toMarkdown(title: string, timestamp: string, data: unknown): string {
    const sections = this.extractSections(data);
    const lines: string[] = [
      `# ${title}`,
      '',
      `**Generated:** ${timestamp}`,
      `**Summary:** ${this.generateSummary(data)}`,
      `**URLs cited:** ${this.countUrls(data)}`,
      '',
    ];

    // Include score if present
    if (data && typeof data === 'object' && 'score' in (data as Record<string, unknown>)) {
      const score = (data as Record<string, unknown>).score as Record<string, unknown>;
      if (score.total !== undefined) {
        lines.push(`## Opportunity Score: ${score.total}/100`);
        lines.push('');
        if (score.verdict) lines.push(`**Verdict:** ${score.verdict}`);
        if (score.confidence) lines.push(`**Confidence:** ${score.confidence}`);
        if (score.breakdown && typeof score.breakdown === 'object') {
          lines.push('', '| Signal | Score |', '|--------|-------|');
          for (const [k, v] of Object.entries(score.breakdown as Record<string, number>)) {
            lines.push(`| ${k.replace(/_/g, ' ')} | ${v} |`);
          }
        }
        lines.push('');
      }
    }

    for (const section of sections) {
      lines.push(`## ${section.heading}`, '');
      for (const f of section.findings) {
        lines.push(`- **${f.text}**`);
        if (f.source_url) lines.push(`  - Source: ${f.source_url}`);
        if (f.subreddit) lines.push(`  - Subreddit: r/${f.subreddit}`);
        if (f.score) lines.push(`  - Score: ${f.score}`);
        if (f.date) lines.push(`  - Date: ${f.date}`);
        lines.push('');
      }
    }

    lines.push('---', `*Generated by Reddit Intelligence Agent*`);
    return lines.join('\n');
  }

  private countUrls(data: unknown): number {
    const json = JSON.stringify(data);
    const urls = json.match(/https?:\/\/reddit\.com[^\s"]+/g);
    return urls ? new Set(urls).size : 0;
  }

  private countDataPoints(data: unknown): number {
    if (!data || typeof data !== 'object') return 0;
    const d = data as Record<string, unknown>;
    let count = 0;
    for (const val of Object.values(d)) {
      if (Array.isArray(val)) count += val.length;
    }
    return count;
  }
}
